services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    instances: 1
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 7525322231:AAHTKL7544IejblJaxkh223GHaixriix52A
